### ISSUE TITLE
Error writing event to Kinesis

### ISSUE THREAD

**Issue by RyuJungDae** [samcday/logstash-output-kinesis#1]
Hi, I want logstash output kinesis.
but error message view

===============================================================================
message=>"Error writing event to Kinesis", :exception=>com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages., :event=>#<LogStash::Event:0x5739e2f7 @metadata={"path"=>"/var/log/nginx/api.oregon.access.log", "partition_key"=>"-"}
===============================================================================

logstash config file

===============================================================================
output
{
  kinesis {
    stream_name => "cwlTest1-KinesisSubscriptionStream-EW4WU6QL3HDQ"
    region => "ap-northeast-1"
    aggregation_enabled => false
    event_partition_keys => ["[field1]", "[field2]"]
  }
}
===============================================================================

What problem this error message?
How modified issue?

please help me.

**Comment by samcday** [comment]
@RyuJungDae just a hunch, are you passing AWS credentials to your Logstash process?

If you check your stdout / stderr logs from Logstash, you should see messages from the "Kinesis Producer Library" (which this gem uses) - check those for any more meaningful info.

**Comment by samcday** [comment]
hi @RyuJungDae I'm going to close this issue out due to inactivity. If this is still an issue for you, please feel free to reopen and provide more info! :)
