### ISSUE TITLE
bundle error

### ISSUE THREAD

**Issue by ofhk** [samcday/logstash-output-kinesis#12]
Hi 

we get this error when building the plugin:
~/logstash-output-kinesis$ bundler install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Could not find gem 'logstash-output-kinesis' in source at `.`.
Source contains 'logstash-output-kinesis' at: 2.1.0 java

Can you please help?

Thanks,
Oliver

**Comment by samcday** [comment]
Hi @ofhk - are you definitely using JRuby 1.7 when you build?

**Comment by samcday** [comment]
@ofhk README has been updated, but be sure to use [rvm](https://rvm.io) and run `rvm use --install .` when you are in the logstash-output-kinesis repo.
