### ISSUE TITLE
Installing kinesis output plugin on a amazon linux box...

### ISSUE THREAD

**Issue by trekr5** [samcday/logstash-output-kinesis#14]
Hello,

I'm trying to install my kinesis plugin onto my logstash instance and have it push logs into my AWS kinesis stream.

I'm running logstash 2.0 on an amazon linux box and have put the kinesis plugin into the /etc/logstash/conf.d/ config directory. When I check my logstash.log, I receive the following error:

_The error reported is: 
Couldn't find any output plugin named 'kinesis'. Are you sure this is correct? Trying to load the kinesis  output plugin resulted in this error: no such file to load -- logstash/outputs/kinesis_

I know that the path /logstash/output/kinesis would be for a windows box. 

Have I put the kinesis output plugin in the right place on my logstash linux box? 

Many thanks

**Comment by samcday** [comment]
Hi @trekr5 - generally you should use the [`plugin`](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html) command provided by Logstash for installing plugins.
