### ISSUE TITLE
Is it compatible with Logstash 5.x?

### ISSUE THREAD

**Issue by jlory** [samcday/logstash-output-kinesis#17]

**Comment by mglee72** [comment]
It doesn't seem so.

**Comment by samcday** [comment]
Yeah I don't believe this is compatible with LS 5.x+. PRs welcome :)

**Comment by samcday** [comment]
Thanks to @gregsterin we now have [logstash-output-kinesis 5.0.0](https://rubygems.org/gems/logstash-output-kinesis/versions/5.0.0-java) with Logstash 5.x compatibility :)
