### ISSUE TITLE
Someday, one of kinesis Stream's process shutdown.

### ISSUE THREAD

**Issue by Jonghwa-Park** [samcday/logstash-output-kinesis#19]
Dear samcday,
I really appreciate you to develop this perfect application. 
I am recently using your application for my project.
But someday, I found some different point especially kinesis stream output process.

When stream data sent time processed by logstash output plugin to our system,
I figure out the kinesis output plunin process count is important which is running daemon as process,
when if the process count is 3, the output data is correct.
But, the count is below than 3, then our output data is incorrect.

So, I wanna if you this issue already known, please tell me how to do handle over.

1) Is there appropreate daemon process count? fixed 3 count?
If then, each process have each role? or only for using parallel processing

2) When comes to the time shutdown one of the daemon process?
for instance when logstash is busy.. or kinesis stream is not busy so itself shut down case..
any case is useful for me.

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
