### ISSUE TITLE
error with Logstash 5.4.2

### ISSUE THREAD

**Issue by jayswan** [samcday/logstash-output-kinesis#25]
I get this error when trying to run this plugin with logstash 5.4.2:

`Pipeline aborted due to error {:exception=>java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries, :backtrace=>["com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(com/amazonaws/services/kinesis/producer/KinesisProducer.java:856)", "com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(com/amazonaws/services/kinesis/producer/KinesisProducer.java:245)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", "RUBY.register(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-kinesis-5.1.0-java/lib/logstash/outputs/kinesis.rb:82)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.register(/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:17)", "RUBY.register(/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:41)", "RUBY.register_plugin(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:268)", "RUBY.register_plugins(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.register_plugins(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279)", "RUBY.start_workers(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288)", "RUBY.run(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:214)", "RUBY.start_pipeline(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:398)", "java.lang.Thread.run(java/lang/Thread.java:745)"]}`

Any ideas on how to fix this or what causes it?

**Comment by samcday** [comment]
Hmmm that's not a very useful backtrace. It's telling us that KPL failed to extract the native binaries to `/tmp` but it's not telling us *why*. Is there any more output or is that it?

**Comment by jjensn** [comment]
I've seen this before; his /tmp isn't writeable. Rookie mistake

**Comment by jayswan** [comment]
I'm no longer using this plugin so I'm going close the issue.
