### ISSUE TITLE
Kinesis Firehose target results in no error but no output

### ISSUE THREAD

**Issue by ensslen** [samcday/logstash-output-kinesis#26]
When I run the attached kinesis_waves.conf and pass the short.csv nothing shows up in Kinesis if the target is a kinesis firehose. CloudWatch Metric's UserRecordsPut is zero, as are the other measures.  Everything works if the target is a ordinary kinesis stream.

I'm running logstash 5.6.0 with my logstash.yml file is entirely commented out on OSX 10.13 with java 1.8.0_131-b11.

Is this intended behavior?

[short.csv.txt](https://github.com/samcday/logstash-output-kinesis/files/1412928/short.csv.txt)
[kinesis_waves.conf.txt](https://github.com/samcday/logstash-output-kinesis/files/1412929/kinesis_waves.conf.txt)

[logstash-plain.log](https://github.com/samcday/logstash-output-kinesis/files/1412919/logstash-plain.log)

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
