### ISSUE TITLE
Amazon Kinesis Data Streams will install ATS certificates

### ISSUE THREAD

**Issue by Everley1993** [samcday/logstash-output-kinesis#27]
On February 9, 2018 at 9AM PST Amazon Kinesis Data Streams will install ATS certificates[1]. Producer clients older than version 0.12.6 will fail to write records to Kinesis at this point because these clients do not support ATS certificates.

**Comment by gfawcettpq** [comment]
It looks like the 2.x branch at least (that's what we're stuck using) just requires a gradle bump and a minor change to the create_kpl_config method (.setPort > .setKinesisPort)

**Comment by Jackyjjc** [comment]
I have created a PR forit: https://github.com/samcday/logstash-output-kinesis/pull/28

**Comment by Jackyjjc** [comment]
Created a PR for 2.x: https://github.com/samcday/logstash-output-kinesis/pull/29 @gfawcettpq can you help testing my PR? I've done some limited testing locally. I ran the unit test, ran logstash 2.6 with the plugin but I wasn't able to test all the features.

**Comment by gfawcettpq** [comment]
I've performed some limited integration testing with the 0.12.6 version and it looks ok.
I built a new version of our Docker image with the updated gem and attached an instance of it to our pre-production logstream and configured it to output to a separate kinesis stream so I could identify the traffic.
I don't see any errors and throughput seemed reasonable.  We only use a small subset of the configuration options though (stream, region and randomized_partition_key)

**Comment by niklasR** [comment]
Here the changes in 0.12.6: https://github.com/awslabs/amazon-kinesis-producer/releases/tag/v0.12.6

Might be worth at some point to consider upgrading to the latest (0.12.8 at the moment), but if that requires more testing, it's probably better to get v0.12.6 out as soon as possible.

Thanks for your work on this, by the way!
