### ISSUE TITLE
Is it compatible with Logstash 6.x?

### ISSUE THREAD

**Issue by Gauravshah** [samcday/logstash-output-kinesis#32]
Planning to use this for logstash 6. 
Did not find any breaking changes between 5 & 6 for plugins:
https://www.elastic.co/guide/en/logstash/current/breaking-changes.html

**Comment by samcday** [comment]
I guess it should work, can you simply install it and see?

**Comment by dnk8n** [comment]
I find that bin/logstash-plugin install logstash-output-kinesis only works on 5.6.7 and below.

The error output I get:

```plaintext
Validating logstash-output-kinesis
Installing logstash-output-kinesis
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 6.2.1)

  In Gemfile:
    x-pack (= 6.2.1) java depends on
      logstash-core (= 6.2.1) java

    logstash-input-syslog (>= 0) java depends on
      logstash-filter-grok (>= 0) java depends on
        logstash-core (>= 5.6.0) java

    x-pack (= 6.2.1) java depends on
      logstash-core (= 6.2.1) java

    logstash-output-kinesis (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
The command '/bin/sh -c bin/logstash-plugin install logstash-output-kinesis' returned a non-zero code: 1
```

**Comment by dnk8n** [comment]
@samcday (Forgot to mention you in comment above)

**Comment by dnk8n** [comment]
@samcday Is there any work to be done to get this pluging supported on Logstash 6? I am happy to give it a go. As far as I can see its just a case of removing a strict conditional expression to include 6.x? The plugin should install and work once that is done?

**Comment by samcday** [comment]
@dnk8n yeah I think that's about all that's necessary. I did the first part locally but I just haven't gotten around to testing that the plugin still functions correctly in a 6.x pipeline.

If you can take a look and get a PR up I would be very grateful! I think you'll also want to update the `.ruby-version` and `.travis.yml` build matrix to use the correct version of JRuby that Logstash 6.x ships with.

**Comment by dg3feiko** [comment]
looking forward to use this output with Logstash 6, thanks for all great jobs

**Comment by samcday** [comment]
[`5.1.2`](https://rubygems.org/gems/logstash-output-kinesis/versions/5.1.2-java) will happily run on Logstash 6.x.
