### ISSUE TITLE
Does it emit records in batches/

### ISSUE THREAD

**Issue by modsaid** [samcday/logstash-output-kinesis#33]
While configuring my logstash instance, I noticed that the plugin is outputting to kinesis stream using `kinesis:PutRecord`  instead of `kinesis:PutRecords`

is there a way to configure the plugin to use `PutRecords` in batches? @samcday

**Comment by samcday** [comment]
That's up to the underlying KPL library. But IIRC it will not use `kinesis:PutRecords` since batched implementation is significantly more complex when it comes to partial failure modes.

Instead, KPL is all about record-level aggregation. Check out the README for more info on that.
