### ISSUE TITLE
Write Throughput Exceeded

### ISSUE THREAD

**Issue by Xaelias** [samcday/logstash-output-kinesis#34]
Hi,

I am using your plugin to backhaul a whole bunch of data from kafka to kinesis.
And right now, I'm exceeding the write throughput.

I was just wondering, since I don't see anything explicit in the logs, what the behavior of logstash was in this case.
I would assume you just retry failed logs until they succeed but I wanted to double check with you :-)

Thanks!

**Comment by jjensn** [comment]
He's got it written in the README...

https://github.com/samcday/logstash-output-kinesis#backpressure

**Comment by samcday** [comment]
What @jjensn said :)
