### ISSUE TITLE
Plugin is not producing logs of underlying KPL

### ISSUE THREAD

**Issue by vhartikainen** [samcday/logstash-output-kinesis#36]
Seems like there is no SLF4J Binding at all in the package. Thus the following log entries are printed and no output is produced in the logs from KPL library.
´´´
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
´´´

I have created a PR (https://github.com/samcday/logstash-output-kinesis/pull/35) as a fix candidate for this. 
Feel free to comment and suggest improvements.

**Comment by samcday** [comment]
[`5.1.2`](https://rubygems.org/gems/logstash-output-kinesis/versions/5.1.2-java) is published which addresses this issue.

**Comment by Jackyjjc** [comment]
If we also port this fix back to 2.x branch that would be great! :)

**Comment by samcday** [comment]
Logstash 2.4 has been end of life for a few months now, so I don't think I'm going to backport this fix sorry
