### ISSUE TITLE
Log message duplication issues

### ISSUE THREAD

**Issue by joekerr1995** [samcday/logstash-output-kinesis#39]
Around mid May we received a notification from the AWS team stating that we needed up upgrade KPL versions due to deprecation as we were running an older version of this logstash plugin at the time.
We upgraded to Logstash 5.x and installed the latest version of this plugin and things seemed to be fine. 
AWS then emailed us again to notify that the change on their back end has been applied.

This occurred around the 22nd June 2018 and since then we have found that we are seeing log message duplication from between 2x to 180x and after investigation we believe that this is occurring when being pushed to Kinesis via this plugin.

Has anyone else experienced this?

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
