### ISSUE TITLE
Complex types used in event partition keys cause serialization errors

### ISSUE THREAD

**Issue by samcday** [samcday/logstash-output-kinesis#4]
If you try to use field `foo` in the event partition key, but `foo` is an array or object, then the plugin fails.

**Comment by carlosrdrz** [comment]
Do you have any more info about this?
I think I'm being affected by this issue, but I'm currently using the default partition key. I've tried with the  random uuid, and I found the same issue.

I'm using Amazon Lambda to log the events that goes to my Kinesis Stream, and I have the impression that the partition key is being included in the `data` field somehow.

This is an example of the kind of messages I'm getting on my lambda instances (in this case, with the default `-` partition key)
```����{"@version":"1","@timestamp":"2011-05-11T08:39:15.000Z", ... [omitted] ...}```

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
