### ISSUE TITLE
Example IAM policy? AccessDenied

### ISSUE THREAD

**Issue by atkinsj** [samcday/logstash-output-kinesis#40]
I'm testing with the following policy:

```{
      "Effect": "Allow",
      "Action": [
        "firehose:*",
        "kinesis:*",
        "cloudwatch:*",
        "logs:*",
        "events:*"
      ],
      "Resource": [ "*" ]
    },
```

attached to the following role:

```{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "firehose.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

and getting:
`Caused by: com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Access denied (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: $redacted)`

Could you provide an example policy?

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
