### ISSUE TITLE
throughput issue

### ISSUE THREAD

**Issue by raaone7** [samcday/logstash-output-kinesis#41]
Hi Team, 

I am trying to stream logs with a autoscaled logstash gke cluster, with this plugin installed. 
with max_pending_records => 5000

my kinesis shards is set to 100 shards, enough capacity

still i am getting warning messages in my logstash logs 

[2019-02-02T08:48:12,822][INFO ][com.amazonaws.services.kinesis.producer.LogInputStreamReader] [2019-02-02 08:48:12.821877] [0x00000032][0x00007f2e2d5eb700] [info] [processing_statistics_logger.cc:112] Stage 2 Triggers: { stream: 'streampoc1', manual: 9, count: 0, size: 0, matches: 0, timed: 387, KinesisRecords: 477, PutRecords: 396 }
[2019-02-02T08:48:26,861][WARN ][logstash.outputs.kinesis ] Kinesis is too busy - blocking until things have cleared up

happy to do a zoom and show you the issue. 

in my use case, i am planning to stream 10gb of logs in < 30 mins, all the way to kinesis. 

Any help is really appreciated. Please contact me at ramshyam1982@gmail.com if you need more information

**Comment by raaone7** [comment]
![plugin-issue](https://user-images.githubusercontent.com/10722171/52162352-cb9fd180-2726-11e9-91af-211287a1d192.JPG)
image

**Comment by samcday** [comment]
Can you show your Logstash config? Are you using a custom partition key by any chance? Also, if you haven't turned on per-stream metrics for your Kinesis stream, make sure you also do that and look at the throughput for each individual shard. Is there a shard that is getting saturated more than the others?

**Comment by samcday** [comment]
Also full disclosure, it's been a couple of years since I really did anything at scale with Kinesis, so my troubleshooting assistance might be a little rusty and outdated ;)

**Comment by raaone7** [comment]
> Also full disclosure, it's been a couple of years since I really did anything at scale with Kinesis, so my troubleshooting assistance might be a little rusty and outdated ;)

Can you please defer this to an expert who can support this. I am planning to use this plugin at production scale. aka. 100gb per 30 mins kind of workload. ? 
do you see any issue with that ?

**Comment by samcday** [comment]
Can you please defer this to an expert who can support this.

Who might that be? You know this is an open source plugin right? :)

Those numbers sound fine, provided you scale your logstash cluster and Kinesis stream appropriately.

Anyway, the config looks fine, so I suggest you try enabling per-shard metrics and see what's going on there.

**Comment by raaone7** [comment]
:-) yes understand,  was wondering if we can connect to the core contributors to get an expert advice. 

I appreciate the work been done so far to get it up and running. wanted to complement it with production user. 

Sure will share the per shard metrics, it would be interesting to see that. will load test and keep you posted. 

any other advice you can think off. is it possible i can run through the configuration with yourself for 15 mins over a call. i would feel a lot more confident in what i am doing

**Comment by samcday** [comment]
Core contributors of this plugin or of Logstash? This plugin is not affiliated with the official Logstash team, nor with the authors of the KPL library from Amazon. It's just a third party plugin I wrote that marries the two together.

In addition to the Kinesis per-shard metrics, you can also [enable KPL metrics](https://github.com/samcday/logstash-output-kinesis#metrics) to give you more insight.

The backpressure could be caused by any number of things. Your Kinesis stream may not be sized appropriately. There might be network bottleneck between you and the Kinesis endpoint (is us-east-1 close enough to where you're running this from?). Your CPU might be too slow (KPL aggregates records together which is actually quite CPU intensive). Metrics are the key here :)

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
