### ISSUE TITLE
Does this support the Firehose output

### ISSUE THREAD

**Issue by vaibhavt19** [samcday/logstash-output-kinesis#44]

**Comment by rodgjame** [comment]
From my experience it does not support the Firehose output out-of-the-box. What you will need to do is create a Kinesis Data Stream and set your `stream_name` in the Logstash config to that. Then you can connect your Data Stream to any Kinesis consumer (in this case you would connect the Data Stream to a Firehose).

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
