### ISSUE TITLE
This Plugin is unstable, as Certificate files are removed after 3 days

### ISSUE THREAD

**Issue by Randy-312** [samcday/logstash-output-kinesis#45]
The implementation of this plugin with the KPL on the server results in the certificate files being removed after 3 days.

As documented here: https://github.com/awslabs/amazon-kinesis-producer/issues/81
And apparently fixed in KPL version 12.8: https://github.com/awslabs/amazon-kinesis-producer/pull/165

Since the current version of KPL this is using is 12.5 based, we still have the issue.
We're going to attempt a workaround on our AMI, but I wanted to document this for anyone else looking to use this output.

**Comment by smolkuva** [comment]
would like to see this fixed too

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
