### ISSUE TITLE
endpoint setting not supported

### ISSUE THREAD

**Issue by ghost** [samcday/logstash-output-kinesis#48]
In order to test locally with something like Localstack, an `endpoint` setting is required. Trying to add an `endpoint => "${KINESIS_ENDPOINT}"` setting results in `[logstash.outputs.kinesis ] Unknown setting 'endpoint' for kinesis`

currently testing with logstash 7.5.1

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!
