### ISSUE TITLE
Not all records make it into Kinesis unless I pass the --debug flag to logstash

### ISSUE THREAD

**Issue by eoconnor** [samcday/logstash-output-kinesis#6]
I'm running Logstash 2.0.0 on a MacBook Pro (10.10.5), using the logstash-output-kinesis plugin to send the output to a Kinesis stream in us-east-1. I've configured Logstash to read from stdin and am piping a large file of Apache log events into Logstash.

In looking at the CloudWatch stats (as well as the stats generated by my Spark job, which is reading the events from the Kinesis stream), I observed that I never got as many records going into Kinesis as I expected. The test file I'm using contains 152,925 total events. Of those, 7 are malformed and so get rejected by Logstash, meaning that I would expect to see 152,918 events going into Kinesis. However, what I was observing was that about 50,000-55,000 events would make it into Kinesis each time (it varied a bit per test run).

To try to get some insight into what was going on, I included the --debug flag on the command line when starting Logstash. Suddenly, I was seeing all 152,918 events making it into Kinesis. If I removed the --debug flag, it went back to about 50,000-55,000 events. I tried it both ways a few times, and the results were consistent each time. I also tried using the --verbose flag instead of the --debug flag, but that still resulted in only 50,000-55,000 events getting into Kinesis. Only the --debug flag gave me 100% of the expected events.

Here's the command I use to ingest the Apache log file that results in 50,000-55,000 events getting into Kinesis:

`bin/logstash -f logstash-stdin.conf < myApacheLogEvents.txt`

And here's the command that results in 100% of events getting into Kinesis:

`bin/logstash --debug -f logstash-stdin.conf < myApacheLogEvents.txt`

And here's the config I'm using for the logstash-output-kinesis plugin in my Logstash config file:

```
output {
  #stdout {
  #  codec => json
  #}

  kinesis {
    stream_name => "dreams-webonenike-logs"
    region => "us-east-1"
    #metrics_level => "none"
    access_key => "xxx"
    secret_key => "xxx"
    randomized_partition_key => true
    aggregation_enabled => false
  }
}
```
As a test, I tried commenting out the kinesis output and uncommenting the stdout output. In that case, I saw that I got 100% of my events out of Logstash, even without including the --debug flag. This suggest to me that whatever is happening involves the Kinesis plugin, and not just Logstash itself.

**Comment by samcday** [comment]
Heya @eoconnor - thanks for submitting this issue! I haven't had time to properly read and digest it yet. However, one thing that jumped out at me is you pasted your credentials and I got those in an email notification. There are others who watch this repo so I think they would have received that notification too. You should definitely invalidate those credentials ASAP.

**Comment by eoconnor** [comment]
Yes, I realized my mistake after I posted this issue. I've gone ahead and invalidated those credentials. Thanks!

**Comment by eoconnor** [comment]
Just wanted to leave a quick note to mention that I confirmed this same behavior when running Logstash on an EC2 instance in AWS.

**Comment by samcday** [comment]
Hey @eoconnor - I have a feeling this might relate to https://github.com/awslabs/amazon-kinesis-producer/issues/21

I've realised that a bit of a flaw with this logstash plugin as it's currently implemented is that there's no backpressure. If Logstash itself is able to process 100k records in a short period of time and then provide them to this plugin for output, this plugin will gleefully accept all 100k and write them to KPL, which is a running child process daemon. Of course, writing 100k records to Kinesis is actually a lot (depending on how many shards you have, I guess).

When I get some time in the next couple of days I'm going to push a commit that checks how many outstanding records KPL currently has enqueued, and then waits for them to flush if its exceeded a (configurable) threshold. We'll see if that helps with your issue.

**Comment by eoconnor** [comment]
Cool, thanks for the feedback and the efforts to look into this issue!

**Comment by samcday** [comment]
Hey @eoconnor I've just pushed up version `1.6.0` and `2.1.0` of this gem which introduce [Backpressure](https://github.com/samcday/logstash-output-kinesis#backpressure). Can you give the new version a spin and see if it addresses your issue?

**Comment by eoconnor** [comment]
Thanks @samcday! I just tried 3 test runs with version 2.1.0 of the plugin (on Logstash 2.1.0), using my original test file containing 152,925 records. On the first test run, I actually saw 153,425 records go into Kinesis, or 500 more than are in my test file. On the next two test runs, I saw exactly 152,925 records go into Kinesis both times, or exactly as many as are in my test file. So, kind of odd, but certainly much better!

On all 3 test runs, I saw a bunch of these log statements getting output:

`Kinesis is too busy - blocking until things have cleared up {:level=>:warn}`

On the first test run, I saw these log statements:

`
[2015-12-07 15:20:03.815150] [0x0000000108a52000] [error] [io_service_socket.h:229] Error during socket read: Operation canceled; 0 bytes read so far (kinesis.us-east-1.amazonaws.com:443)
[2015-12-07 15:20:09.837400] [0x0000000108a52000] [error] [io_service_socket.h:200] Error during socket write: Operation canceled; 376832 bytes out of 1493152 written (kinesis.us-east-1.amazonaws.com:443)
`
And then later, towards the end of the run, this one:

`[2015-12-07 15:25:32.969200] [0x0000000108a52000] [error] [http_client.cc:148] Failed to open connection to monitoring.us-east-1.amazonaws.com:443 : short read`

I saw this log statement on the second test run:

`[2015-12-07 15:29:27.462755] [0x0000000103856000] [error] [io_service_socket.h:229] Error during socket read: End of file; 0 bytes read so far (kinesis.us-east-1.amazonaws.com:443)`

And I saw this log statement on the third and final test run:

`[2015-12-07 15:51:06.173583] [0x0000000106bc6000] [error] [io_service_socket.h:200] Error during socket write: Operation canceled; 1425408 bytes out of 1491581 written (kinesis.us-east-1.amazonaws.com:443)`

**Comment by samcday** [comment]
Sweet! I'll close this out as resolved now then. Feel free to get in touch if you have any further issues! :)

**Comment by rhoml** [comment]
@samcday so 1.6.x will be the next recommended for logstash 1.5?

**Comment by samcday** [comment]
@rhoml Aye!

**Comment by rhoml** [comment]
:+1:
