### ISSUE TITLE
Logstash & Kinesis losing logs

### ISSUE THREAD

**Issue by rhoml** [samcday/logstash-output-kinesis#7]
Hey man,
This still needs more debugging but I've relized that logstash might be losing logs when using kinesis. Not 100% sure if this has anything to do with https://github.com/samcday/logstash-output-kinesis#noisy-warnings-about-error-during-socket-read but the number of logs that get lost if pretty big. +50% in some cases. I will continue digging into it though.

**Comment by rhoml** [comment]
We have traced the missing logs to the `record-aggregation` in logstash `1.5.4-1`. If we disable log aggregation I see the increase of logs arriving to ES but it causes a huge delay in log ingestion ~30mins delay. Will try to increase kinesis workers to see if we can speedup things or even logstash filter nodes.

**Comment by samcday** [comment]
Hey @rhoml - how are you going with this? Still need help?

**Comment by samcday** [comment]
(Sorry for the delay BTW, got buried under my inbox after coming back from a 3 week holiday :D)

**Comment by rhoml** [comment]
@samcday no worries, we found out that we had this plugin configured to aggregate logs and the logstash input kinesis doesn't support it. When we disabled aggregation then we were having problems with kinesis throughput so =/.

We decided to change kinesis to rabbitmq but the throughput is quite high for rabbit. We can close this issue since it isn't related to the output.
