### ISSUE TITLE
jar dependencies conflict with elasticsearch output plugin

### ISSUE THREAD

**Issue by sonya** [samcday/logstash-output-kinesis#9]
On various servers running Java 8, I had the latest `logstash-output-elasticsearch` plugin installed concurrently with this plugin, and Logstash was consistently crashing shortly after startup with a `NoMethodError` exception on `set_validate_after_inactivity`.

It turns out the elasticsearch plugin depends on `manticore` which calls [`setValidateAfterInactivity`](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html#setValidateAfterInactivity%28int%29) which was added in v4.4 of `httpclient`. `manticore` requires version 4.5 of `httpclient` in its gemspec, while this plugin ships with 4.3. I believe Java 8 is somehow loading these such that the 4.3 versions takes precedence.

I am able to fix the issue locally (and haven't run into any other problems) by swapping the the `httpclient` and `httpcore` files for newer versions in this plugin's `runtime-jars` folder.

**Comment by samcday** [comment]
Hmmm interesting - what version of Logstash proper are you using? I haven't updated this plugin in a couple of months, and there's been a few releases of LS since then.

**Comment by sonya** [comment]
I am currently using 2.3. I believe that was the version I was using when I created this issue, although I was using 2.2 until shortly before and IIRC experienced the same dependency conflict between this package and the elasticsearch. Thanks!

**Comment by samcday** [comment]
I've updated KPL to 0.12.5 and pushed version 5.0.0 of this plugin. If this is still an issue feel free to reopen.
